import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import TextField from "@mui/material/TextField";
import { Button } from "@mui/material";
import fire_big from "../../../../public/img/fire_big.svg";
import fire_small from "../../../../public/img/fire_small.svg";
import stack from "../../../../public/img/stack.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    // <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <div className="flex items-center  min-w-[1000px]">
      <div className="w-1/3 h-224 flex flex-col gap-5 text-center px-16 py-74 expand-item">
        <p className="text-3xl font-bold pb-10 pl-5 pr-5">
          Welcome!
          <br />
          Sign in to continue
        </p>
        {/* <h2 className="text-2x1 font-bold">Sign in to continue</h2> */}
        <div className="w-full">
          <TextField
            id="outlined-disabled"
            label="Enter your email address"
            sx={{ width: "100%" }}
            variant="outlined"
          />
        </div>
        <div className="w-full">
          <TextField
            id="outlined-password-input"
            label="Password"
            type="password"
            autoComplete="current-password"
            sx={{ width: "100%" }}
          />
        </div>
        <div className="w-full flex justify-end">
          <a href="#" className="underline">
            Forgot password?
          </a>
        </div>
        <div className="w-full">
          <Button variant="contained" sx={{ width: "100%" }}>
            Sign in
          </Button>{" "}
        </div>
      </div>

      <div className="w-2/3 bg-color-made h-224 m-3 rounded-lg hide-item">
        <div className="absolute  right-3 bottom-7">
          <Image
            src={fire_big}
            width={400}
            height={300}
            alt="Picture of the author"
            className="hide-item"
          />
        </div>
        <div className="absolute right-3 bottom-10 rounded-lg">
          <Image
            src={fire_small}
            width={200}
            height={140}
            alt="Picture of the author"
            className="hide-item"
          />
        </div>
        <div className="relative left-12 top-20 w-90">
          <Image
            src={stack}
            width={500}
            height={308}
            alt="Picture of the author"
          />
        </div>
      </div>
    </div>
    // </body>
    // </html>
  );
}
