import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createTheme } from "@mui/material";
// import { ThemeProvider } from "@mui/material/styles";

// const customTheme = createTheme({
//   palette: {
//     primary: {
//       main: "#1d563d", // Your desired main color (e.g., orange)
//     },
//     secondary: {
//       main: "#4CAF50", // Another custom color
//     },
//   },
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ThemeProvider theme={customTheme}> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        {children}
      </body>
      {/* </ThemeProvider> */}
    </html>
  );
}
